apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml           
namespace: kyverno 
helmCharts:
  - name: kyverno
    releaseName: kyverno
    repo: https://kyverno.github.io/kyverno/
    version: v3.5.0       # pin to a specific version!
    valuesFile: kyverno-values.yaml
  
