NODES = [
  { name: "controlplane", ip: "10.0.0.10" },
  { name: "worker1", ip: "10.0.0.11" },
  { name: "worker2", ip: "10.0.0.12" },
]

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  NODES.each do |node|
    config.vm.define node[:name] do |node_config|
      node_config.vm.hostname = node[:name]
      node_config.vm.network "private_network", ip: node[:ip]

      node_config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 2
      end

      # Optional: Enable provisioning
      # node_config.vm.provision "ansible_local" do |ansible|
      #   ansible.playbook = "/vagrant/ansible/playbook.yaml"
      #   ansible.inventory_path = "/vagrant/ansible/inventory.yaml"
      # end
    end
  end
end
