apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-default-namespace
spec:
  # Enforce the policy immediately on admission
  validationFailureAction: enforce
  # Wildcard policy not allowed in background mode. Set spec.background=false to disable background mode for this policy rule
  background: false
  rules:
    - name: deny-in-default
      # Only consider CREATE and UPDATE operations
      preconditions:
        - key: "{{ request.operation }}"
          operator: In
          value: ["CREATE", "UPDATE"]
      match:
        resources:
          # 'kinds: *' means “all resource kinds”
          kinds: 
           - "*"
          namespaces:
            - default
      validate:
        message: "Deployments into the default namespace are not allowed. Please use a dedicated namespace."
        deny: {}
